---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: debian-8.6

suites:
  - name: default
    run_list:
      - recipe[wen-deploy::default]
  #    - recipe[wen-deploy::gittify]
    attributes:
