here = File.basename FileUtils.pwd

desc 'bundle up this cookbook and its dependencies'
task :package do
  `berks package ../#{here}.tgz`
end

desc 'publish to github'
task :publish do
  require 'git'
  Dir.chdir '../' do
    g = Git.open '.'
    begin
      g.branch 'gh-pages'
      g.add '.'
      g.commit "new #{here} cookbook version"
      g.push g.remote('gh-pages')
  #  rescue Git::GitExecuteError
  #    puts 'Nothing new to publish'
    end
  end
end
