desc 'bundle up this cookbook and its dependencies'
task :package do
  here = File.basename FileUtils.pwd
  `berks package ../#{here}.tgz`
end

desc 'publish to github'
task :publish do
  require "pry" ; binding.pry
  
end
